### ISSUE TITLE
Poor mapping in V3LOOP

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/MiCall#370] opened 2016-11-08 21:46 UTC
## Update ##
This issue has evolved into a problem with low mapping counts in the V3LOOP region. It will be combined with putting all of HIV on a continuous seed reference in issue #366.

* [x] Try soft clipping. (Maps almost everything, but G2P had lots of reads that were missing big chunks from soft clipping.)
* [x] Try running G2P directly off trimmed FASTQ.
* [x] Generate coverage and counts files from results of FASTQ G2P, by generating an equivalent of the aligned file.
* [x] Report G2P overlap with bowtie2 alignment in V3LOOP.
* [x] Align deletions to codon boundaries.
* [x] Validate the new FASTQ G2P by comparing %X4 with 454 results for some of the validation runs that Phil did.
* [x] ~~Report insertions from G2P alignment, or create a separate issue.~~ (moved to #390)

## Original ##
Just saw this from one of the samples that ran over the weekend.  Step 5 appears to have failed, with no reads being properly remapped.  I looked at the records and the stderr log says:

```
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
```

but the return code was 0.  Unfortunately the sandbox has already been purged so I was unable to go in and look to see if any output was actually generated.

It's possible this is a Kive bug, but I have a stronger suspicion that that's a Bowtie error.

* [x] ~~Find cause of run-time error.~~ (Unable to reproduce.)
* [x] Look at differences between consensus and reference.

**Comment by donkirkby** [comment] 2016-11-14 19:19
Do you have the run date and sample number? We could try to reproduce it.

**Comment by rhliang** [comment] 2016-11-14 19:20
Yep, I'll email it to you right now.

**Comment by donkirkby** [comment] 2016-11-14 19:37
The problem occurred with sample 67206A-V3-3 in the 04 Nov 2016 run. Rerunning it generated the exact same error message, so I'll try to debug it.

**Comment by donkirkby** [comment] 2016-11-14 19:53
So far, that sample has had six replicates. The other five of them had a tiny number of reads that mapped to HIV-env, then the remapping step grabbed most of the other reads (many thousands).

Check why the consensus is so different from the reference, also check what's causing the runtime error.

**Comment by donkirkby** [comment] 2016-11-16 21:05
It looks like the problem may be related to the adapter sequences described in issue #312. The `prelim_map` step doesn't use bowtie2's `--local` option, so it doesn't try soft clipping the ends of each read. If enough reads map using those options, the `remap` step uses the `--local` option to try and map as many reads as it can.

Here's what I found when I ran replicates 1 and 3 through `prelim_map` with and without the `--local` option.

|                       |  rep1|rep1 local|  rep3|rep3 local|
|-------------------|--------|-------------|--------|-------------|
|**raw**           |47744|     47744|42274|      42274|
|**prelim**       |        8|       1958|        0|        1737|
|**remapped** |46186|     47666|         |       42219|
|**unmapped**|  1558|           78|         |             55|

I'm going to see what the results from this sample look like after issue #312 is closed.

As for the run-time error, I couldn't reproduce it on my workstation.

**Comment by donkirkby** [comment] 2016-11-25 19:15
Now that issue #312 is closed, I tested this again. Trimming the adapters didn't seem to have much effect on this sample. It only allowed 27 more reads to map in the `prelim_map` step, and all of them just trimmed the last three bases. 24 were read 1, 3 were read 2.

1651 read 1 reads and 1616 read 2 reads contained a full adapter sequence, but removing the adapter sequences didn't let them map to the reference. I tried blasting some of the remaining sequence, and it mapped to a different HIV-env reference.

Perhaps we need to use more than one HIV-env seed reference, so I'll experiment with some other references.

**Comment by donkirkby** [comment] 2016-11-25 19:22
Another thing to try is to dump the sequence that is getting soft clipped, and see if anyone recognizes it as some strange version of HIV-env or some weird fold during the PCR.

This looks like it will take a lot more investigation, so I'm going to push it to the next milestone.

**Comment by donkirkby** [comment] 2017-01-27 17:58
Another sample with very low counts in the preliminary mapping step is 68068-V3 from the 06 Jan 2017 run.

**Comment by donkirkby** [comment] 2017-01-27 18:11
The plan is to select a group of HIV references by building a phylogenetic tree and picking a diverse set. We should probably pick many X4 representatives. Then we will map a lot of the old 454 data through the Micall pipeline to see how the following measures change as we add more references:

* fraction mapped successfully in `prelim_map`
* fraction assigned a G2P score
* agreement between G2P scores from Micall and 454 pipelines

**Comment by donkirkby** [comment] 2017-02-03 00:21
Here's the plan after discussion with Richard H. and Chanson: try two options.

* Try using a shorter seed reference for V3LOOP that is just the region we look at, plus a few bases for margin. See if bowtie2 will map that with soft clipping disabled.
* Try allowing soft clipping at the prelim_map step, but only look at fully mapped reads to determine the seeds to use. If there are fewer than 100 fully mapped reads, use the soft clipped reads to determine the seeds to use. Pay particular attention to how this change affects the HCV seed choice with all those subtypes.

**Comment by donkirkby** [comment] 2017-02-07 19:06
Bowtie2 would not map a long read onto a short reference, so the first option won't work.

Soft clipping looks promising, most of the 454 data mapped nicely, just looking at the number of reads that mapped. I didn't look at coverage.

Since I thought we had had problems with the HCV genotypes and soft clipping, I tried some of those samples. Some genotypes and subtypes changed compared to 7.6, but I haven't found anything that's clearly worse, yet.

One curious result is sample D62240-HCV from the 16 Nov 2015 run. When I ran it with soft clipping enabled and many HIV seeds, it stopped mapping reads to HLA, and mapped 5748 reads to HIV1-F1-CY-JF683771-seed. However, those reads all mapped fewer than 50 nucleotides. When I ran it with soft clipping enabled and only one HIV seed, it went back to mapping HLA.

**Comment by donkirkby** [comment] 2017-02-08 01:33
I figured out why sample D62240-HCV stopped mapping HLA and mapped a bunch of short reads. They are two unrelated changes.

* The short reads are a bunch of 12 nucleotide reads that all mapped to one of the new HIV references. They map there because we added the new reference.
* The HLA stopped mapping, because I did the mapping with the basespace version of the pipeline. That version excludes the HLA seeds, because they're not ready for external use.

**Comment by donkirkby** [comment] 2017-02-16 19:48
Try making G2P go right back to the trimmed FASTQ files, and see if we can just align the reads against the reference that G2P uses. Think about how to deal with coverage and other quality control.

**Comment by donkirkby** [comment] 2017-04-11 18:36
Running directly off the FASTQ file looks promising, so I'll do more validation.

When comparing against the 454 results, I found two differences:

1. 454 doesn't validate that the sequence starts and ends with Cysteines, MiCall does.
2. 454 validates that the mapped region is at least 99 nucleotides, but it leaves the dashes in when counting. A big deletion in the middle will be accepted by the 454, but rejected by MiCall.

**Comment by donkirkby** [comment] 2017-04-18 20:46
I validated 14 samples from the 19-Sep-2016.M04401 run, and the majority of each sample's replicates agreed with the 454 result. The samples included four that were non-B.

**Comment by donkirkby** [comment] 2017-04-21 22:21
I have coverage maps from the G2P pairwise mapping, but it has two problems:
1. The G2P overlap from bowtie2 results might not align properly with the G2P results, either because bowtie2 used a different seed, or because it had insertions in the consensus.
2. The G2P coverage will always have a deletion at position 27, because of the difference between the seed and the coordinate reference.

Suggestion: use a custom seed for G2P that matches the coordinate reference. Then align that seed to whatever seed gets used for bowtie2 mapping, and use that alignment to report the G2P overlap.

Consider reporting three coordinates in `nuc.csv` and `amino.csv`: coordinate reference, seed reference, and consensus sequence.

**Comment by donkirkby** [comment] 2017-05-03 17:13
I ran the new `fastq_g2p.py` against the 69 samples from the 12-Jun-2015 run that we had 454 results for, and the results matched well. There were 4 sets of triplicate samples that had some disagreement with the 454 results, but all of those would have been rejected because of low counts or low percentage of valid reads.

* 63463A - one replicate reports R5, right at the border of 2% X4 sequences. The percentage valid for all three replicates ranges from 70% to 74%. The 454 reports X4 at 2.3%, which matches the other two replicates from MiCall.
* E102448 and 63472A - two replicates report X4, but at very low counts. The 454 reports R5.
* 63531A and 63461A - one replicate reports X4, but at very low counts. The 454 reports R5.

I'm closing this issue, because the test passed.

**Closed by donkirkby** 2017-05-03 17:13 UTC
Labels: bug, in progress
